### ISSUE TITLE
Query regarding supplementary material and attention maps

### ISSUE THREAD

**Issue by AntiLibrary5** [yolish/multi-scene-pose-transformer#1]
Hi,
Thank you for your work, indeed interesting application of DETR to camera-APR problem. I wanted to know
1. if the complete paper along with the supplementary material is available somewhere.
2. your choice for using learned embeddings instead of sine embeddings like in DETR: is it because no difference in performance?  I cannot recall reading about it in your paper on arxiv.
3. how do you overlay the attention weights through the CNN over the image to produce the plots in Figure 3. and Figure 4.?

Thank you.

**Comment by yolish** [comment]
Thank you for your interest in our work.
1. The latest version of the main text and suppl. material will be available from the ICCV website
2. We found learned embedding to yield better results compared to sine embedding
3. We have used the standard visualization of attention maps, by taking the attention weights from the last layer and resizing them. We will add the visualization code to the repo in the next days so you can try it.

**Comment by AntiLibrary5** [comment]
Thank you for the clarification and the hint for attention maps. For anyone looking for the same meanwhile (source: https://github.com/facebookresearch/detr/issues/47#issuecomment-645062804, but the difference is that the attention map won't rely on the objects detected i.e. object queries is pose regression are different in a sense), you can easily use a forward hook to get decoder attention weights (C x HW):
decoder_weights = []
hook = [model.transformer_t.decoder.layers[-1].multihead_attn.register_forward_hook(
            lambda self, input, output: decoder_weights.append(output[1])
        )]
and then resizing them:
attn = decoder_weights[0, 0].view(H,W)
where H,W would be the size of feature maps of the last layer you used for the CNN backbone.

**Comment by yolish** [comment]
Hi, I've just pushed a toy script which demonstrates the plotting of attention maps - hope this will help.
