### ISSUE TITLE
ModuleNotFoundError: No module named 'efficientnet_pytorch'

### ISSUE THREAD

**Issue by FrankwaP** [yolish/multi-scene-pose-transformer#2]
Hi and thank you for sharing your code !

When loading the backbone using the `efficient-net-b0.pth` file, one gets this error:
```
[…]
  File "…/multi-scene-pose-transformer/models/transposenet/backbone.py", line 36, in __init__
    backbone = torch.load(backbone_model_path)
[…]
ModuleNotFoundError: No module named 'efficientnet_pytorch'
```

The fix seems to be: `pip install efficientnet-pytorch`, can you confirm ?

**Comment by yolish** [comment]
Hi, yes  - I can confirm this module is needed. In order to make the set up easier I've just pushed a requirements.txt file (see README for instructions). Hope this helps!
